!function(){var f,h=this&&this.U||function(a,b){function c(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)},aa={error:0,keyup:1,scroll:2,resize:3,unload:4,online:5,mouseup:6,offline:7,mousedown:8,mouseover:9,touchstart:10,beforeunload:11,visibilitychange:12,0:"error",1:"keyup",2:"scroll",3:"resize",4:"unload",5:"online",6:"mouseup",7:"offline",8:"mousedown",9:"mouseover",10:"touchstart",11:"beforeunload",12:"visibilitychange"};
function k(a,b,c,d,e,g){var l=this;this.g=a;this.b=b;this.c=c;this.h=d;this.F=e;this.f=g;a.forEach(function(a){return a.i(l.a.bind(l)).a()});this.b.bind([5,7],function(){ba(l,function(a){return navigator.onLine?a.a():a.c()})})}
k.prototype.a=function(){var a=ca(this.c);if(!a.a){var b=this.f,c=Date.parse((new Date).toUTCString());b.a.intr=b.identification.P=c;m(b,b.a);a:{var b=this.h,c={id:a.id,F:this.F,type:a.type,reliable:a.reliable},a={data:a.metrics},d={};if(c.reliable&&da(b.b,c.id,d)){if(a=d.M,0>--a.retries){b.app.H();break a}}else a={message:a,metrics:c,retries:b.config.distribution.relaibleMessages.retries},n(b.b,c.id,a);c=a;b.a&&(a=b.m+"?t="+c.metrics.type,b.f.b(b.g).f(a,c))}}};
k.prototype.j=function(a){a||this.a();ba(this,function(a){return a.c()})};function ba(a,b){a.g.forEach(function(a){return b(a)})}
var ea={visitId:3,version:6,screenX:16,screenY:17,browser:18,location:7,visitorId:2,projectId:1,messageId:5,eventIds:21,pageviewId:4,timestamp:31,attention:32,timeOnPage:12,numOfClicks:14,scrollReach:13,jsErrorCount:11,engagementTime:9,lackOfInterest:30,browserVersion:19,documentReferrer:8,domContentLoaded:10,durationSinceLastVisit:15,3:"visitId",6:"version",16:"screenX",17:"screenY",18:"browser",7:"location",2:"visitorId",1:"projectId",5:"messageId",21:"eventIds",4:"pageviewId",31:"timestamp",32:"attention",
12:"timeOnPage",14:"numOfClicks",13:"scrollReach",11:"jsErrorCount",9:"engagementTime",30:"lackOfInterest",19:"browserVersion",8:"documentReferrer",10:"domContentLoaded",15:"durationSinceLastVisit"};function fa(){}fa.prototype.a=function(a){var b={};a.forEach(function(a){return b[ea[a.type]]=a.value});return JSON.stringify(b)};function q(a){this.a=a;this.f=this.b=!1;this.c=0;this.a.bind([6],this.i.bind(this));this.a.bind([8],this.h.bind(this))}q.prototype.h=function(a){this.g=a.target};
q.prototype.i=function(a){this.g===a.target&&this.c++};q.prototype.s=function(){return{value:this.c,type:14}};function r(){}function n(a,b,c){a[b.toString()]=c}function da(a,b,c){return(a=a[b.toString()])?(c.M=a,!0):!1}function t(a){this.i=a;this.b=this.h.bind(this);this.a=new r;this.c=[9,6,1,2,3];this.f=[8,9,6,1,12];this.g=[2,3,5,7,0,11,4];ga(this)}function ga(a){a.i.a.is.o&&(a.c.push(10),a.f.push(10));a.f.concat(a.g).forEach(function(b){a.a[b]=[]});ha(a)}
t.prototype.bind=function(a,b){ia(this,a,b)};function ja(a,b,c){b.forEach(function(b){if(a.a){b=a.a[b];var e=b.indexOf(c);-1<e&&b.splice(e,1)}})}function ka(a,b){ia(a,[11,4],b,!0)}function ia(a,b,c,d){void 0===d&&(d=!1);var e=d?function(a){return a.splice(0,0,c)}:function(a){return a.push(c)};b.forEach(function(b){return e(a.a[b])})}t.prototype.h=function(a){this.a[aa[a.type]].forEach(function(b){return b(a)})};t.prototype.j=function(){this.a=null;la(this)};
function ha(a){function b(a){return a.addEventListener}u(b,window,a.g,a.b);u(b,document,a.f,a.b)}function la(a){function b(a){return a.removeEventListener}u(b,window,a.g,a.b);u(b,document,a.f,a.b)}function u(a,b,c,d){c.forEach(function(c){c=aa[c];a(b).apply(b,[c,d,!1])})}function w(a,b){void 0===a&&(a=!1);void 0===b&&(b=!0);this.b=a;this.f=b}w.prototype.s=function(){return{type:this.type,value:this.a()}};function x(a){w.call(this,!0,!1);this.identification=a.identification}h(x,w);
function y(a){x.call(this,a);this.type=4}h(y,x);y.prototype.a=function(){return this.identification.J};var ma=/function ([^\(]+)/;function z(a,b){var c;if(!(c=b)){var d;if("string"===typeof a)d=a;else{if(!((c=a.name)||(c=a.toString().match(ma),c=c&&0<c.length&&c[1]))){c=[];var e=a.prototype;for(d in e)c.push(d);c=c.join("")}d=c}c=d}this.a=c}z.prototype.toString=function(){return this.a};function na(a){a.w=1;return a}
function A(){this.a=[];this.b=new r;var a=oa({C:this,B:function(a){return a},l:this,u:1,w:0});n(this.b,new z(A),a)}A.prototype.j=function(a){for(;0<this.a.length;)this.a.shift().j(a)};function B(a,b){return pa(a,null,b)}function qa(a,b){var c=pa(Object.getPrototypeOf(b).constructor,a,null);c.w=0;c.u=1;C(c,b)}function pa(a,b,c){var d=D;a=new z(a,b);c=oa({l:d,B:c,w:0,u:0});n(d.b,a,c);return c}A.prototype.resolve=function(a,b,c,d,e){return this.f.apply(this,[a,null,b,c,d,e])};
A.prototype.f=function(a,b,c,d,e,g){var l;l=Array.prototype.slice.call(arguments,2);var p,v=ra(this,a,b);v?(p=v.C,p||(l=l||[],l.splice(0,0,v.l),p=v.B.apply(null,l),C(v,p)),l=p):l=null;return l};function E(a,b){var c,d=ra(a,b,null);return d?function(a,b,l,p){a=[d.l,a,b,l,p];c=d.C;c||(c=d.B.apply(null,a),C(d,c));return c}:function(){return null}}function ra(a,b,c){var d;b=new z(b,c);c={};da(a.b,b,c)&&(d=c.M);return d}function sa(a){this.B=a}h(sa,function(){});
function C(a,b){1!==a.w&&(a.C=b);0===a.u&&b.j&&a.l.a.push(b);a.G&&a.G(a.l,b)}function oa(a){var b=new sa(a.B);b.u=a.u;b.w=a.w;b.C=a.C;b.l=a.l;b.G=a.G;return b}function F(){}F.prototype.i=function(a){this.m=a;return this};F.prototype.f=function(){this.m()};function G(a){this.config=a;this.g=0;this.b=1;this.h=!1;this.maxFetchInterval=this.config.metrics.maxFetchInterval}h(G,F);G.prototype.a=function(){var a=this,b=this.h?this.maxFetchInterval:ta(this);this.v=setTimeout(function(){a.f();a.a()},b)};
G.prototype.c=function(){clearInterval(this.v)};G.prototype.j=function(){this.c()};function ta(a){var b=a.g+a.b,c=1E3*b;if(c>a.maxFetchInterval)return a.h=!0,a.maxFetchInterval;a.g=a.b;a.b=b;return c}function H(a){w.call(this,!0,!1);this.c=a;this.type=1}h(H,w);H.prototype.a=function(){return this.c};function I(){w.apply(this,arguments);this.type=17}h(I,w);I.prototype.a=function(){return window.innerHeight};function ua(){}
ua.prototype.a=function(a){var b=[];a.forEach(function(a){b.push(a.type+"="+encodeURIComponent(a.value))});return b.join("&")};function J(){w.apply(this,arguments);this.type=16}h(J,w);J.prototype.a=function(){return window.innerWidth};function va(a){this.b=a}h(va,F);function K(a){this.c=a;this.f=this.b=!1;this.g=this.h.bind(this);this.a=0;this.c.bind([2,3],this.g)}
K.prototype.h=function(){var a=(document.documentElement.scrollTop||document.body.scrollTop)/((document.documentElement.scrollHeight||document.body.scrollHeight)-(window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight))*100,a=Math.abs(Math.round(Math.min(100,a)));this.a=Math.max(a,this.a);100===this.a&&ja(this.c,[2,3],this.g)};K.prototype.s=function(){return{value:this.a,type:13}};function L(a){this.f=this.b=!1;this.g=0;this.c=!1;this.h=0;this.m=a.navigationStart}
function M(a){var b=Date.now();a.c&&(a.h+=b-a.g,a.g=b)}L.prototype.s=function(){M(this);return{type:this.a(),value:Date.now()-this.m-this.h}};function N(a,b){L.call(this,b);this.i=a;this.i.bind([12],this.v.bind(this))}h(N,L);N.prototype.a=function(){return 12};N.prototype.v=function(){document.hidden?(this.c=!0,this.g=Date.now()):(M(this),this.c=!1)};function wa(){w.apply(this,arguments);this.type=6}h(wa,w);wa.prototype.a=function(){return 1};
function xa(){this.b=/ (\w+)(?:\/([\w\.]+))? (?:(\([^\)]+\)) )?/img;this.a=ya(this);var a=this.a.D,b=this.a.is;this.f=0===a.type&&!b.o||3===a.type&&9<=a.version||2===a.type&&534<=a.version||5===a.type&&25<=a.version&&!b.o||4===a.type&&5.1<=a.version&&10>=a.version||7===a.type&&9<a.version&&!b.o}
function ya(a){for(var b=" "+navigator.userAgent+" ",c=window.XMLHttpRequest,d={},e;e=a.b.exec(b);)d[e[1]]={value:e[2],extra:e[3]},a.b.lastIndex--;a={is:{o:!1},D:{version:6}};e=a.D;var g=d.Mozilla&&d.Mozilla.extra?d.Mozilla.extra:null;a.supports={sendBeacon:!!navigator.sendBeacon,V:c&&"withCredentials"in new XMLHttpRequest};if(d.Opera)return e.version=0,e.name="Opera",e.type=1,a;if(d.Edge)return e.type=0,e.name="Edge",e.version=parseInt(d.Edge.value),a.is.o=-1!==b.indexOf("Windows Phone; "),a;if(g&&
(b=g.indexOf("MSIE "),-1<b+g.indexOf("; Trident/")&&(b=-1!==b?b:g.indexOf("; rv:"),-1!==b)))return e.type=7,e.name="Internet Explorer",e.version=parseFloat(g.substr(b+5,3)),a.is.o=-1!==g.indexOf("; Touch")||-1!==g.indexOf("; IEMobile/"),a;if(d.Firefox&&d.Firefox.value)return e.type=5,e.name="Firefox",e.version=parseFloat(d.Firefox.value),a.is.o=g&&-1!==g.indexOf("Android; "),a;if((d.Chrome&&d.Chrome.value||d.CriOS&&d.CriOS.value)&&!d.Version)return e.type=3,e.name="Chrome",e.version=parseFloat(d.Chrome?
d.Chrome.value:d.CriOS.value),a.is.o=d.CriOS||g&&-1!==g.indexOf("; Android "),a;if(d.Safari){e.name="Safari";if(g&&-1!==g.indexOf("; Android ")&&d.AppleWebKit&&d.AppleWebKit.value)return e.type=2,e.version=parseFloat(d.AppleWebKit.value),a.is.o=!0,a;g&&-1===g.indexOf("Windows")&&d.Version&&d.Version.value&&(e.type=4,e.version=parseFloat(d.Version.value),a.is.o=!!d.Mobile)}return a}function za(a){w.call(this);this.type=18;this.c=a.a}h(za,w);za.prototype.a=function(){return this.c.D.name};
function Aa(a){x.call(this,a);this.type=3}h(Aa,x);Aa.prototype.a=function(){return this.identification.K};function O(a){this.f=this.b=!1;this.c=Math.pow(2,53)-1;this.v=a.navigationStart;this.m=this.g=this.c=this.i=0}function Ba(a,b){500>Date.now()-a.v||(a.m++,a.h=b,a.g+=a.h,a.c=Math.min(a.h,a.c),a.i=Math.max(a.h,a.i))}O.prototype.s=function(){return{value:{sum:this.g,max:this.i,min:this.c,count:this.m},type:this.a()}};
function Ca(a,b,c){this.b=a;this.g=b;this.c=c;this.a=Date.now();this.b.bind(a.c,this.f.bind(this))}Ca.prototype.f=function(){var a=Date.now(),b=a-this.a;1E3>=b?Ba(this.g,b):1E3<b&&5E3>b&&Ba(this.c,b);this.a=a};function Da(a){x.call(this,a);this.type=2}h(Da,x);Da.prototype.a=function(){return this.identification.L};function Ea(){w.apply(this,arguments);this.type=8}h(Ea,w);Ea.prototype.a=function(){return document.referrer};function Fa(){}
function P(a,b,c){L.call(this,c);this.v=a;this.config=b;this.i=0;this.v.bind(a.c,this.S.bind(this));Ga(this)}h(P,L);P.prototype.a=function(){return 9};function Ga(a){clearTimeout(a.i);a.i=setTimeout(function(){a.c=!0;a.g=Date.now()},a.config.metrics.inactivityTime)}P.prototype.S=function(){M(this);this.c=!1;Ga(this)};P.prototype.j=function(){clearTimeout(this.i)};
function Ha(a,b,c,d){var e=this;this.l=b;this.config=c;this.app=d;b=this.j.bind(this);this.a=c.transport.mainChannel;setTimeout(b,c.identification.visitTimeSpan);a.bind([4,11],function(){return e.j()});this.b=E(this.l,this.a+" channel")}function Ia(a){return a.l.resolve(a.a+" serializer")}Ha.prototype.j=function(a){this.a=this.config.transport.terminalChannel;Ja(this.f);this.b=E(this.l,this.a+" channel");this.l.j(a);this.app.I()};Ha.prototype.H=function(){this.j(!0)};
function Ka(a){this.id=a;this.b=!0;this.f=!1}Ka.prototype.s=function(){return{value:this.id,type:5}};function La(a,b){for(var c=1;c<arguments.length;c++);var d=Array.prototype.slice.call(arguments,1);return a.replace(/\{(\d+)\}/g,function(a,b){return d[b]})}function Ma(a){this.b=a;this.g=this.f.bind(this)}h(Ma,va);Ma.prototype.a=function(){this.b.bind([0],this.g)};Ma.prototype.c=function(){ja(this.b,[0],this.g)};function Na(){}function Q(){return Math.floor(Math.random()*Oa)}
var Oa=Math.pow(2,53)-1;function Pa(){w.apply(this,arguments);this.type=7}h(Pa,w);Pa.prototype.a=function(){return location.href};function Qa(a){for(var b=arguments.length,c,d,e,g,l,p=1;p<b;p++)if(c=arguments[p])for(d in c)e=a[d],g=c[d],a!==g&&(g&&(Ra(g)||(l=Array.isArray(g)))?l?(l=!1,a[d]=g.slice()):(e=e&&Ra(e)?e:{},a[d]=Qa(e,g)):void 0!==g&&(a[d]=g));return a}
function Ra(a){return"object"!==(null==a?a+"":"object"===typeof a||"function"===typeof a?Sa[Ta.call(a)]||"object":typeof a)||a.nodeType||a===window||a.constructor&&!Ua.call(a.constructor.prototype,"isPrototypeOf")?!1:!0}var Sa={},Ta=Sa.toString,Ua=Sa.hasOwnProperty;function Va(a,b,c){this.config=c;this.b=0;Wa(this)}
function Wa(a){var b=!1,c=Xa();c&&(b=Ya(a,c,function(){var b=Date.parse((new Date).toUTCString())-c.intr;a.b=Math.round(b/6E4);b<a.config.identification.visitTimeSpan||(c.vst=Q());c.pgv=Q();c.intr=Date.parse((new Date).toUTCString());return c}));b||m(a,a.a={pgv:Q(),vst:Q(),vstr:Q(),intr:Date.parse((new Date).toUTCString())});Za(a)}
function Xa(){var a;a:{var b;a=b=0;var c=document.cookie.split(";");b="ctm=";for(var d=0;d<c.length;d++){var e=c[d];if(0===e.trim().indexOf(b)){b=a+e.length;a=a+e.split("=")[0].length+1;a=document.cookie.substring(a,b);break a}a+=e.length+1}a=null}if(a)try{return JSON.parse(a)}catch(g){}return null}function Za(a){a.identification={K:a.a.vst,L:a.a.vstr,J:a.a.pgv,P:a.a.intr}}function Ya(a,b,c){return $a(b)?(b=c?c(b):b,m(a,b),a.a=b,!0):!1}
function $a(a){return["vst","pgv","vstr","intr"].every(function(b){var c;return(c=a[b])?!isNaN(c):!1})}function m(a,b){var c=JSON.stringify(b),d=a.config.identification.expirationDays,e="";d&&(e=new Date,e.setTime(e.getTime()+864E5*d),e="; expires="+e.toUTCString());document.cookie="ctm="+c+e+"; path=/;"}function ab(a){this.b=a}function R(a,b){a.reset();setTimeout(function(){a.b.A.reject(b)},a.b.waitInterval)}function bb(a){this.a=a}
bb.prototype.f=function(a,b){navigator.sendBeacon(a+"&"+b.message.data)?this.a.A.resolve(b):this.a.A.reject(b)};function cb(a){w.call(this);this.type=19;this.c=a.a}h(cb,w);cb.prototype.a=function(){return this.c.D.version};function S(a){this.b=a;this.a=new Image}h(S,ab);S.prototype.f=function(a,b){var c=this,d=b.message.data;this.a.onload=function(){c.reset();c.b.A.resolve(b)};this.a.onerror=function(){R(c,b)};this.a.src+=a+"&"+d+"&r="+Date.now()};
S.prototype.reset=function(){this.a=this.a.onerror=this.a.onload=null};function db(a){w.call(this);this.c=a;this.type=15}h(db,w);db.prototype.a=function(){return this.c.b};function T(a){this.b=a;this.a=new XMLHttpRequest}h(T,ab);
T.prototype.f=function(a,b){var c=this,d=this.a,e=b.message.data;try{d.open("POST",a),d.timeout=3E4,d.setRequestHeader("Content-Type","text/plain"),this.a.onreadystatechange=function(){4===d.readyState&&(200===d.status?(c.reset(),c.b.A.resolve(b)):R(c,b))},d.onload=function(){c.reset();c.b.A.resolve(b)},d.onerror=d.ontimeout=d.onabort=function(){R(c,b)},d.send(e)}catch(g){R(this,b)}};
T.prototype.reset=function(){this.a=this.a.onabort=this.a.ontimeout=this.a.onerror=this.a.onload=this.a.onreadystatechange=null};function eb(a){this.c=a;this.f=this.b=!1;this.a=0;this.c.bind([0],this.g.bind(this))}eb.prototype.g=function(){this.a++};eb.prototype.s=function(){return{value:this.a,type:11}};
function fb(a,b,c,d,e){var g=this;this.app=a;this.config=b;this.c=c;this.l=d;this.f=e;this.a=!1;this.b=new r;this.m=b.transport.url;this.g={A:{reject:this.h,resolve:this.i},waitInterval:b.distribution.relaibleMessages.waitInterval};this.a=navigator.onLine;this.c.bind([5,7],function(){return g.a=navigator.onLine})}fb.prototype.i=function(a){a.metrics.F.resolve(a.metrics)};fb.prototype.h=function(a){a.metrics.F.reject(a.metrics)};
function gb(a,b,c,d,e){var g=this;this.metrics=a;this.config=c;this.c=d;this.g=e;this.reliable=!0;this.a=this.b=0;this.f=Ia(e);ka(b,function(){Ja(g)})}function Ja(a){a.a=2;a.f=Ia(a.g);a.metrics=a.metrics.filter(function(a){return a.b})}function ca(a){var b=a.reliable?a.b:++a.b,c=a.c(b);return{id:b,type:a.a,reliable:a.reliable,metrics:a.f.a(a.metrics.concat([c]).map(function(a){return a.s()}))}}function hb(a,b){b.reliable&&(a.reliable=!1,a.a=1,a.metrics=a.metrics.filter(function(a){return!a.f}))}var V;
function ib(){return Qa({metrics:{inactivityTime:2E4,maxFetchInterval:5E3,providers:"BrowserMetric EventIdsMetric TimeOnPageMetric ScrollReachMetric JSErrorCountMetric NumberOfClicksMetric BrowserVersionMetric ResolutionWidthMetric ResolutionHeightMetric LackOfInterestMetric DurationSinceLastVisitMetric EngagementTimeAggregatorMetric".split(" ")},identification:{expirationDays:365,visitTimeSpan:18E5,integrationMessageFormat:"CT2MappingTag_{0}_{1}_{2}_{3}",integrationMethod:function(){return self.ClickTaleEvent}},
transport:{url:"https://",mainChannel:"main",terminalChannel:"terminal"},distribution:{relaibleMessages:{retries:2,waitInterval:1E3}}},self.ClickTaleMonitor.Settings.config)}function jb(a){w.call(this);this.c=a;this.b=!1;this.f=!0;this.type=10}h(jb,w);jb.prototype.a=function(){return this.c.domContentLoadedEventEnd-this.c.navigationStart};function W(){this.g=this.f=this.b=!1;this.h=[]}W.prototype.s=function(){return{value:this.h,type:21}};W.prototype.c=function(){this.g=!1};
W.prototype.a=function(){this.g=!0};W.prototype.i=function(a){this.m=a;return this};function X(a){this.g=a;this.b=!1}h(X,F);X.prototype.resolve=function(a){hb(this.g,a)};X.prototype.reject=function(a){a.reliable&&this.b&&this.f()};X.prototype.a=function(){this.b=!0};X.prototype.c=function(){this.b=!1};function kb(a){O.call(this,a)}h(kb,O);kb.prototype.a=function(){return 32};function lb(a){O.call(this,a)}h(lb,O);lb.prototype.a=function(){return 30};
function Y(a,b){var c=this;this.a=a;this.f=b;mb(function(){nb(c)&&ob(c)})}var D;function mb(a){Z||(/complete|interactive/.test(document.readyState)?a():document.addEventListener("DOMContentLoaded",a,!1))}
function ob(a){var b=D.resolve("Disposer");D.resolve("IdentificationService");Z=!0;D.resolve("Hub");D.resolve("CompositeInactivity");D.resolve("MetricsReader");D.resolve("DistributionService");b.f=D.resolve("MetricAggregator");a.f&&a.f(a);if(self.ClickTaleGlobal)ClickTaleGlobal.scripts.integration.onReady(function(){var b=V||(V=ib()),d=b.identification.integrationMethod(),b=b.identification.integrationMessageFormat,e=D.resolve("IdentificationService").identification,b=La(b,a.a,e.L,e.K,e.J);d(b)})}
function nb(a){var b=self.performance,c=V||(V=ib()),d=new xa;return d.f?(D=new A,a.b=new W,B("Hub",function(){return new t(d)}),qa(null,d),pb(d.a,c),B("IdGenerator",function(){return new Na}),B("VersionMetric",function(){return new wa}),B("LocationMetric",function(){return new Pa}),B("CookiesService",function(){return new Fa}),B("BrowserMetric",function(){return new za(d)}),B("ResolutionWidthMetric",function(){return new J}),qa("EventIdsMetric",a.b),B("ProjectIdMetric",function(){return new H(a.a)}),
B("DocumentReferrerMetric",function(){return new Ea}),B("ResolutionHeightMetric",function(){return new I}),na(B("IdMetric",function(a,b){return new Ka(b)})),B("AttentionMetric",function(){return new kb(b.timing)}),B("BrowserVersionMetric",function(){return new cb(d)}),B("ScrollReachMetric",function(a){return new K(a.resolve("Hub"))}),B("JSErrorCountMetric",function(a){return new eb(a.resolve("Hub"))}),B("LackOfInterestMetric",function(){return new lb(b.timing)}),B(c.transport.mainChannel+" serializer",
function(){return new fa}),B("NumberOfClicksMetric",function(a){return new q(a.resolve("Hub"))}),B("PeriodicalNotifierRule",function(){return new G(c)}),B(c.transport.terminalChannel+" serializer",function(){return new ua}),B("DOMLContentLoadedTimeMetric",function(){return new jb(b.timing)}),B("TimeOnPageMetric",function(a){return new N(a.resolve("Hub"),b.timing)}),B("Disposer",function(b){return new Ha(b.resolve("Hub"),b,c,a)}).u=1,B("MetricsPromise",function(a){return new X(a.resolve("MetricAggregator"))}),
B("VisitIdentificationMetric",function(a){return new Aa(a.resolve("IdentificationService"))}),B("VisitorIdentificationMetric",function(a){return new Da(a.resolve("IdentificationService"))}),B("DurationSinceLastVisitMetric",function(a){return new db(a.resolve("IdentificationService"))}),B("PageViewIdentificationMetric",function(a){return new y(a.resolve("IdentificationService"))}),B("EngagementTimeAggregatorMetric",function(a){return new P(a.resolve("Hub"),c,b.timing)}),B("DistributionService",function(b){return new fb(a,
c,b.resolve("Hub"),b,b.resolve("Disposer"))}),B("CompositeInactivity",function(a){return new Ca(a.resolve("Hub"),a.resolve("LackOfInterestMetric"),a.resolve("AttentionMetric"))}),B("IdentificationService",function(a){return new Va(a.resolve("IdGenerator"),a.resolve("CookiesService"),c)}),B("MetricAggregator",function(a){var b=c.metrics.providers.map(function(b){return a.resolve(b)}),b=b.concat([a.resolve("VersionMetric"),a.resolve("LocationMetric"),a.resolve("ProjectIdMetric"),a.resolve("DocumentReferrerMetric"),
a.resolve("VisitIdentificationMetric"),a.resolve("DOMLContentLoadedTimeMetric"),a.resolve("VisitorIdentificationMetric"),a.resolve("PageViewIdentificationMetric")]);return new gb(b,a.resolve("Hub"),c,E(a,"IdMetric"),a.resolve("Disposer"))}),B("MetricsReader",function(a){var b=a.resolve("MetricsPromise");return new k([b,a.resolve("EventIdsMetric"),a.resolve("PeriodicalNotifierRule")],a.resolve("Hub"),a.resolve("MetricAggregator"),a.resolve("DistributionService"),b,a.resolve("IdentificationService"))}),
!0):!1}f=Y.prototype;f.H=function(){this.j(!0)};f.j=function(a){D.resolve("Disposer").j(a)};f.I=function(){Z=!1;this.c&&this.c()};f.T=function(a){this.c=a};f.R=function(){return Z};f.O=function(a){var b=D.resolve("IdentificationService"),c=Xa()||{},c=Qa(c,a);Ya(b,c)&&Za(b)};function pb(a,b){var c=b.transport,d=a.supports.sendBeacon?bb:S;B(c.terminalChannel+" channel",function(a,b){return new d(b)}).u=1;na(B(c.mainChannel+" channel",function(a,b){return new T(b)})).u=1}
f.N=function(a){var b=this.b;-1===b.h.indexOf(a)&&(b.h.push(a),b.g&&b.m())};var Z=!1;Y.container=D;Y.isMonitoring=Z;Y.prototype.stop=Y.prototype.I;Y.prototype.onStop=Y.prototype.T;Y.prototype.dispose=Y.prototype.j;Y.prototype.shutdown=Y.prototype.H;Y.prototype.addEvent=Y.prototype.N;Y.prototype.isMonitoring=Y.prototype.R;Y.prototype.setIdentification=Y.prototype.O;
var qb="object"===typeof module&&"object"===typeof module.exports,ClickTaleMonitor=(qb?module.exports.ClickTaleMonitor:self.ClickTaleMonitor)||{};ClickTaleMonitor.App=Y;qb?module.exports=ClickTaleMonitor:self.ClickTaleMonitor=ClickTaleMonitor; ClickTaleMonitor.version="1.0.1";if (self.ClickTaleMonitor && self.ClickTaleMonitor.Settings) { self.ClickTaleMonitor.Settings.onReady(); }}();
